[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm install',
  'cd server && npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'cd server && node server.js'

